### ISSUE TITLE
Error accessing 'min_date' options key during get_next_available_time() call

### ISSUE THREAD

**Issue by ScottJWalter** [carmoreira/date-time-picker-field#2]
It appears that `$opts['min_date']` isn't always set when `get_next_available_time()` is called, throwing an error at line 280 when PHP attempts to reference it.

PR #1  addresses this.

**Comment by carmoreira** [comment]
Thank you for reporting @ScottJWalter and for the PR! 
I have now fixed this and also applied the same logic to other values.
