### ISSUE TITLE
Searching Strings for non-string Needle

### ISSUE THREAD

**Issue by TylerVigario** [carmoreira/date-time-picker-field#4]
[Passing a non-string needle to string search functions is deprecated in PHP 7.3.](https://www.php.net/manual/en/function.strpos.php)

Could you please elaborate on the intended result here?

https://github.com/carmoreira/date-time-picker-field/blob/b07fabcbb230c47be8d940e3fe62867d3ae6e102/includes/DateTimePicker.php#L182

**Comment by FN17** [comment]
Perfect.
Your code eliminates the error message.
Thanks a lot
Frank
